//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customer_id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string password { get; set; }
        public Nullable<int> cart_id { get; set; }
        public string status { get; set; }
        public string token { get; set; }
        public System.DateTime date_added { get; set; }
    }
}
