//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public int order_status_id { get; set; }
        public int payment_method_id { get; set; }
        public string payment_method { get; set; }
        public string payment_firstname { get; set; }
        public string payment_lastname { get; set; }
        public string payment_address_1 { get; set; }
        public string payment_address_2 { get; set; }
        public string payment_city { get; set; }
        public string payment_postcode { get; set; }
        public string payment_country { get; set; }
        public string shipping_firstname { get; set; }
        public string shipping_lastname { get; set; }
        public string shipping_address_1 { get; set; }
        public string shipping_address_2 { get; set; }
        public string shipping_city { get; set; }
        public string shipping_postcode { get; set; }
        public string shipping_country { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> total { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
