//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int productid { get; set; }
        public string productname { get; set; }
        public string header { get; set; }
        public string shortdesc { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string imagename { get; set; }
        public string status { get; set; }
        public decimal unitprice { get; set; }
        public int quantity { get; set; }
        public int subtract { get; set; }
        public int sort_order { get; set; }
        public int categoryid { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}
