//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int user_id { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string firstname { get; set; }
        public string lastame { get; set; }
        public string email { get; set; }
        public bool status { get; set; }
        public System.DateTime date_added { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    }
}
